### ISSUE TITLE
Add Dockerfile and Docker Compose...

### ISSUE THREAD

**Issue by chrishaley42** [minus-adam/adam-learning#3]
- [ ] Add Dockerfile
- [ ] Add Spotify Docker Plugin
- [ ] Add Docker Compose File

Use the Spotify Docker Plugin for Building your Docker Images
https://github.com/spotify/docker-maven-plugin

Dockerfile should look something like this...
```
FROM FROM java:8

ENTRYPOINT ["java", "-Xms512m", "-Xmx768m", "-jar", "/opt/app_name/app_name.jar"]

CMD [""]

ADD target/*.jar /opt/app_name/app_name.jar
```

https://docs.docker.com/compose/
Docker Compose Example 
```
app_name:
  image: image_name:latest
  ports:
    - "8080:8080"
```
